export const typeStyles: Record<
  string,
  {
    border: string;
    accent: string;
    bg: string;
    from: string;
    to: string;
    solid: string;
  }
> = {
  fire: {
    border: 'border-red-300',
    accent: 'from-red-500 to-red-600 text-white',
    bg: 'bg-red-50',
    from: 'from-red-400',
    to: 'to-orange-200',
    solid: 'bg-red-500',
  },
  water: {
    border: 'border-blue-300',
    accent: 'from-blue-500 to-blue-600 text-white',
    bg: 'bg-blue-50',
    from: 'from-blue-400',
    to: 'to-cyan-200',
    solid: 'bg-blue-500',
  },
  grass: {
    border: 'border-green-300',
    accent: 'from-green-500 to-green-600 text-white',
    bg: 'bg-green-50',
    from: 'from-green-400',
    to: 'to-lime-200',
    solid: 'bg-green-500',
  },
  electric: {
    border: 'border-yellow-300',
    accent: 'from-yellow-400 to-yellow-500 text-black',
    bg: 'bg-yellow-50',
    from: 'from-yellow-300',
    to: 'to-amber-200',
    solid: 'bg-yellow-400',
  },
  psychic: {
    border: 'border-pink-300',
    accent: 'from-pink-500 to-pink-600 text-white',
    bg: 'bg-pink-50',
    from: 'from-pink-400',
    to: 'to-rose-200',
    solid: 'bg-pink-500',
  },
  ice: {
    border: 'border-cyan-300',
    accent: 'from-cyan-400 to-cyan-500 text-white',
    bg: 'bg-cyan-50',
    from: 'from-cyan-300',
    to: 'to-blue-100',
    solid: 'bg-cyan-400',
  },
  dragon: {
    border: 'border-indigo-400',
    accent: 'from-indigo-600 to-violet-600 text-white',
    bg: 'bg-indigo-50',
    from: 'from-indigo-400',
    to: 'to-violet-300',
    solid: 'bg-indigo-600',
  },
  dark: {
    border: 'border-stone-500',
    accent: 'from-stone-700 to-stone-800 text-white',
    bg: 'bg-stone-100',
    from: 'from-stone-500',
    to: 'to-stone-300',
    solid: 'bg-stone-700',
  },
  fairy: {
    border: 'border-fuchsia-300',
    accent: 'from-fuchsia-400 to-pink-400 text-white',
    bg: 'bg-fuchsia-50',
    from: 'from-fuchsia-300',
    to: 'to-pink-200',
    solid: 'bg-fuchsia-400',
  },
  fighting: {
    border: 'border-orange-400',
    accent: 'from-orange-600 to-red-600 text-white',
    bg: 'bg-orange-50',
    from: 'from-orange-400',
    to: 'to-red-300',
    solid: 'bg-orange-600',
  },
  poison: {
    border: 'border-purple-300',
    accent: 'from-purple-500 to-purple-700 text-white',
    bg: 'bg-purple-50',
    from: 'from-purple-400',
    to: 'to-fuchsia-200',
    solid: 'bg-purple-600',
  },
  ground: {
    border: 'border-amber-400',
    accent: 'from-amber-500 to-yellow-600 text-white',
    bg: 'bg-amber-50',
    from: 'from-amber-400',
    to: 'to-yellow-200',
    solid: 'bg-amber-500',
  },
  rock: {
    border: 'border-stone-400',
    accent: 'from-stone-500 to-stone-600 text-white',
    bg: 'bg-stone-50',
    from: 'from-stone-400',
    to: 'to-stone-200',
    solid: 'bg-stone-500',
  },
  bug: {
    border: 'border-lime-400',
    accent: 'from-lime-500 to-green-500 text-white',
    bg: 'bg-lime-50',
    from: 'from-lime-400',
    to: 'to-green-200',
    solid: 'bg-lime-500',
  },
  ghost: {
    border: 'border-violet-400',
    accent: 'from-violet-600 to-purple-800 text-white',
    bg: 'bg-violet-50',
    from: 'from-violet-400',
    to: 'to-purple-200',
    solid: 'bg-violet-600',
  },
  steel: {
    border: 'border-slate-400',
    accent: 'from-slate-400 to-slate-600 text-white',
    bg: 'bg-slate-50',
    from: 'from-slate-300',
    to: 'to-slate-100',
    solid: 'bg-slate-500',
  },
  flying: {
    border: 'border-sky-300',
    accent: 'from-sky-400 to-indigo-400 text-white',
    bg: 'bg-sky-50',
    from: 'from-sky-300',
    to: 'to-indigo-200',
    solid: 'bg-sky-400',
  },
  normal: {
    border: 'border-neutral-300',
    accent: 'from-neutral-400 to-neutral-500 text-white',
    bg: 'bg-neutral-50',
    from: 'from-neutral-300',
    to: 'to-neutral-100',
    solid: 'bg-neutral-400',
  },
  default: {
    border: 'border-gray-200',
    accent: 'from-gray-400 to-gray-500 text-white',
    bg: 'bg-gray-50',
    from: 'from-gray-200',
    to: 'to-gray-100',
    solid: 'bg-gray-400',
  },
};
